<template>
    <div>
        <div>page2</div>
        <div>page2</div>
        <div>page2</div>
        <div>page2</div>
        <div>page2</div>
        <div>page2</div>
        <div>page2</div>
        <div>page2</div>
        <div>page2</div>
        <div>page2</div>
        <div>page2</div>
        <div>page2</div>
        <div>page2</div>
        <div>page2</div>
        <div>page2</div>
        <div>page2</div>
        <div>page2</div>
        <div>page2</div>
        <div>page2</div>
        <div>page2</div>
        <div>page2</div>
        <div>page2</div>
        <div>page2</div>
        <div>page2</div>
        <div>page2</div>
        <div>page2</div>
        <div>page2</div>
        <div>page2</div>
        <div>page2</div>
        <div>page2</div>
        <div>page2</div>
        <div>page2</div>
        <div>page2</div>
        <div>page2</div>
        <div>page2</div>
        <div>page2</div>
        <div>page2</div>
        <div>page2</div>
        <div>page2</div>
        <div>page2</div>
        <div>page2</div>
        <div>page2</div>
        <div>page2</div>
        <div>page2</div>
        <div>page2</div>
        <div>page2</div>
        <div>page2</div>
        <div>page2</div>
        <div>page2</div>
        <div>page2</div>
        <div>page2</div>
        <div>page2</div>
        <div>page2</div>
        <div>page2</div>
        <div>page2</div>
    </div>
</template>